name: Build docs

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - docs
  workflow_dispatch:
  
jobs:

  build-and-upload-artifact:
    name: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install 'setuptools<50.0'
          python -m pip install .[testing,docs]

      - name: Build docs
        run: |
          sed -i 's,https://user-images.githubusercontent.com/17995243/120086403-f1d0b300-c121-11eb-8000-a44a2ac54339.mp4,<video width="640" height="480" controls>
  <source src="https://user-images.githubusercontent.com/17995243/120086403-f1d0b300-c121-11eb-8000-a44a2ac54339.mp4" type="video/mp4">
Your browser does not support the video tag.
</video>,g' .napari/DESCRIPTION.md
          cd docs
          make html
          cd ..
          
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: docs
          path: docs/_build/html
